#+STARTUP: indent
#+STARTUP: hidestars


* Troubleshooting
Troubleshooting is the process of identifying, analyzing, and solving problems.

There are lots of tools that we can use to get more information about the system and what the programs in our system are doing. Tools like tcpdump and Wireshark can show us ongoing network connections, and help us analyze the traffic going over our cables. Tools like ps, top, or free can show us the number and types of resources used in the system. We can use a tool like strace to look at the system calls made by a program, or ltrace to look at the library calls made by the software. 

System calls
Calls that the programs running on your computer make to the running kernel.

** Steps
1. Getting information
   + What to ask the users?
     + What were you trying to do?
     + What steps did you follow?
     + What was the expected result?
     + What was the actual result?
   Reproduce the problems
   Reproduction case: A clear description of how and when the problem appears. A way to verify if the problem is present or not.
2. Finding the root cause of the problem.
3. Performing the necessary remediation.

   
When Load average in last 1 minute is higher than the number of cpu cores in the system, then the system is overloaded.

kill -stop


* Debugging
Debugging is the process of identifying, analyzing, and removing bugs in a system.

Debuggers let us follow the code line by line, inspect changes in variable assignments, interrupt the program when a specific condition is met, and more.


